/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-02 16:09:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;
import org.xson.common.object.XCO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.xson.common.object.XCO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

	String key = cn.gatherlife.wms.business.util.JspUtils.getImageVerifyKey();

      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge, chrome=1\"/>\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\">\n");
      out.write("<meta name=\"renderer\" content=\"webkit\"/>\n");
      out.write("<title>XX大学教育学院</title>\n");
      out.write("<meta name=\"Keywords\" content=\"\">\n");
      out.write("<meta name=\"Description\" content=\"\">\n");
      out.write("<link href=\"img/style18.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"head\">\n");
      out.write("<img width=\"1280\" height=\"230\" src=\"/img/pp.png\"/>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"menu\">    \n");
      out.write("<ul>    \n");
      out.write("<li class=\"hover\"><a href=\"index.jsp\">网站首页</a></li> \n");
      out.write("<li><a href=\"cgzslist.jsp\">成果展示</a></li>\n");
      out.write("<li><a href=\"jxdtlist.jsp\">教学动态</a></li>\n");
      out.write("<li><a href=\"zytzlist.jsp\">重要通知</a></li>\n");
      out.write("</ul>    \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"fenline\"></div>\n");
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("\n");
      out.write("<div class=\"cgfx\">\n");
      out.write("<div class=\"title\">成果展示 <a href=\"cgzslist.jsp\">更多+</a></div>\t\n");
      out.write("<ul>\n");
      out.write("<li class=\"cgzs1\"><a href=\"\" target=\"_blank\" id=\"h1\"><img id=\"c1\" src=\"\"></a><p><a href=\"\" target=\"_blank\" id=\"ct1\"></a></p></li>\n");
      out.write("<li class=\"cgzs2\"><a href=\"\" target=\"_blank\" id=\"h2\"><img id=\"c2\" src=\"\"></a><p><a href=\"\" target=\"_blank\" id=\"ct2\"></a></p></li>\n");
      out.write("<li class=\"cgzs3\"><a href=\"\" target=\"_blank\" id=\"h3\"><img id=\"c3\" src=\"\"></a><p><a href=\"\" target=\"_blank\" id=\"ct3\"></a></p></li>\t\n");
      out.write("</ul>\n");
      out.write("</div>\t\n");
      out.write("\n");
      out.write("<div class=\"cgfxz\">\n");
      out.write("<div class=\"title\">教学动态 <a href=\"jxdtlist.jsp\">更多+</a></div>\t\n");
      out.write("\n");
      out.write("<div class=\"hdyw-pic\" id=\"TeXiao2\">\n");
      out.write("<ul>\n");
      out.write("<li><a href=\"#\" target=\"_blank\" id=\"lb1\"><img id=\"l1\" src=\"\" alt=\"\"></a></li>\n");
      out.write("<li><a href=\"#\" target=\"_blank\" id=\"lb2\"><img id=\"l2\" src=\"\" alt=\"\"></a></li>\n");
      out.write("<li><a href=\"#\" target=\"_blank\" id=\"lb3\"><img id=\"l3\" src=\"\" alt=\"\"></a></li>\n");
      out.write("</ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dtxw20\"></div>\n");
      out.write("<div class=\"dtxw\">\n");
      out.write("<ul id=\"news\">\n");
      out.write("\n");
      out.write("</ul>\t\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\t \n");
      out.write("<div class=\"cgfxr\">\n");
      out.write("<div class=\"title\">\n");
      out.write("教学入口\t\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"hyzx\">\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("<div class=\"delu\">\n");
      out.write("<form name=\"myform\" id=\"myform\" action=\"UserRegResult.asp\" method=\"post\">\n");
      out.write("<ul class=\"mt30\">\n");
      out.write("<li>\n");
      out.write("<span class=\"label\">账号：</span>\n");
      out.write("<input type=\"text\" name=\"UserName\" id=\"UserName\" value=\"\" placeholder=\"请输入账号\"  onkeyup=\"this.value=this.value.replace(/^ +| +$/g,'')\">\n");
      out.write("<div id=\"Nameid\">\n");
      out.write("<p id=\"user_name_msg\" style=\"display: none;\">账号不能为空！！</p>\n");
      out.write("</div>\n");
      out.write("</li>\n");
      out.write("\t\t\t\n");
      out.write("<li>\n");
      out.write("<span class=\"label\">密码：</span>\n");
      out.write("<input type=\"password\" class=\"emialLock\" maxlength=\"20\" id=\"PassWord\" name=\"PassWord\"  placeholder=\"请输入密码\"  onkeyup=\"this.value=this.value.replace(/^ +| +$/g,'')\">\n");
      out.write("<div id=\"Wordid\">\n");
      out.write("<p id=\"password_msg\" style=\"display: none;\">密码不能为空！！</p>\n");
      out.write("</div>\n");
      out.write("</li>\n");
      out.write("\n");
      out.write("<li>\n");
      out.write("<span class=\"label\">身份：</span>\n");
      out.write("<select class=\"select\" id=\"Question\" style=\"width:170px;\">\n");
      out.write("<option value=\"1\">学生</option>\n");
      out.write("<option value=\"2\">教师</option>\n");
      out.write("<option value=\"3\">管理员</option>\n");
      out.write("</select> \n");
      out.write("<div id=\"Wordid2\"></div>\t\t\t\t\n");
      out.write("</li>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("<li>\n");
      out.write("<span class=\"label2\">验证码：</span>\n");
      out.write("<input type=\"text\" class=\"verifycode\" maxlength=\"20\" id=\"verifycode\" name=\"verifycode\"  value=\"\" placeholder=\"请输验证码\"  onkeyup=\"this.value=this.value.replace(/^ +| +$/g,'')\">\n");
      out.write("<img title=\"点击刷新\" align=\"absmiddle\" style=\"margin-right:25px;\" src=\"");
      out.print(request.getContextPath());
      out.write("/jcaptcha/verify.do?key=");
      out.print(key );
      out.write("\" onclick=\"verifyFun()\" id=\"imgVer\">\n");
      out.write("<div id=\"code2\">\n");
      out.write("<p id=\"verifycode_msg\" style=\"display: none;\">验证码不能为空！！</p>\n");
      out.write("</div>\n");
      out.write("</li>\t\t\n");
      out.write("\t\t\t\n");
      out.write("</ul>\n");
      out.write("<ul style=\"padding-top: 0px;\">\n");
      out.write("\t\t    \n");
      out.write("<li>\n");
      out.write("<input type=\"Button\" class=\"btn_reg\" id=\"btnSubmit\" onclick=\"doLogin();\" value=\"登录\">\n");
      out.write("</li>\n");
      out.write("\t\t\n");
      out.write("</ul>\n");
      out.write("</form>\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</div>\n");
      out.write("\t\n");
      out.write("\t\t\n");
      out.write("<div class=\"title\">重要通知</div>\n");
      out.write("<div class=\"dtxwq\">\t\t\t\t\n");
      out.write("<ul id=\"message\">\n");
      out.write("\n");
      out.write("</ul>\n");
      out.write("</div>\t\n");
      out.write("</div>\n");
      out.write("\t\n");
      out.write("</div>\t\n");
      out.write("<div class=\"clear\"></div>\t\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"fenline\"></div>\n");
      out.write("<div class=\"foot\">\n");
      out.write("<p>版权所有Copyright © 2017 XXXX教育学院 All Rights Reserved </p>\n");
      out.write("<p>院办电话：000-00000000 学工办电话：000-00000000  \n");
      out.write("</p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/jquery.yx_rotaion.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap-dist/js/bootstrap.min.js\"></script>\t\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/xco2.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-xco-src2.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gou/mToken_K1.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gou/mToken_K1Plugin.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gou/base64.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(\"#TeXiao1\").yx_rotaion({auto:true});\n");
      out.write("$(\"#TeXiao2\").yx_rotaion({\n");
      out.write("auto:true,\n");
      out.write("css_yx_rotaion_btn:\"yx-rotaion-btn1\",\n");
      out.write("css_left_btn:\"left_btn1\",\n");
      out.write("css_right_btn:\"right_btn1\",\n");
      out.write("css_yx_rotation_title:\"yx-rotation-title1\",\n");
      out.write("css_yx_rotation_t:\"yx-rotation-t1\",\n");
      out.write("css_yx_rotation_focus:\"yx-rotation-focus1\"\n");
      out.write("});\n");
      out.write("\n");
      out.write("//刷新验证码\n");
      out.write("function verifyFun(){\n");
      out.write("\tvar imgVer = document.getElementById(\"imgVer\");\n");
      out.write("\timgVer.src = '");
      out.print(request.getContextPath());
      out.write("/jcaptcha/verify.do?key=");
      out.print(key );
      out.write("&time ='+new Date();\n");
      out.write("}\n");
      out.write("\n");
      out.write("query1();\n");
      out.write("\n");
      out.write("function query1(){\n");
      out.write("\tvar xco=new XCO();\n");
      out.write("\txco.setIntegerValue(\"photo_type\", 0);\n");
      out.write("\t\tvar options ={\n");
      out.write("\t\t\turl:\"/index/photolist.jhtml\",\n");
      out.write("\t\t\tdata:xco,\n");
      out.write("\t\t\tsuccess: manage1\n");
      out.write("\t};\n");
      out.write("\t$.doXcoRequest(options);\t\t\t\t\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("//渲染单个对象\n");
      out.write("function manage1(xco){\n");
      out.write("\tvar total = 0;\n");
      out.write("\tif(xco.getIntegerValue(\"total\")){\n");
      out.write("\t\ttotal = xco.getIntegerValue(\"total\");\n");
      out.write("\t}\n");
      out.write("    var _dataList = xco.getXCOListValue(\"data\");\n");
      out.write("    if(_dataList){\n");
      out.write("\t\tfor ( var i = 0; i < _dataList.length; i++) {\n");
      out.write("\t\t\t$(\"#c\"+(i+1)).attr(\"src\",_dataList[i].getStringValue(\"photo_src\"));\n");
      out.write("\t\t\tvar len = _dataList[i].getStringValue(\"photo_title\").length;\n");
      out.write("\t\t\tif(i==0){\n");
      out.write("\t\t\t\tif(len>28){\n");
      out.write("\t\t\t\t\t$(\"#ct\"+(i+1)).text(_dataList[i].getStringValue(\"photo_title\").substring(0,28)+\"...\");\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t$(\"#ct\"+(i+1)).text(_dataList[i].getStringValue(\"photo_title\"));\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\tif(len>12){\n");
      out.write("\t\t\t\t\t$(\"#ct\"+(i+1)).text(_dataList[i].getStringValue(\"photo_title\").substring(0,12)+\"...\");\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t$(\"#ct\"+(i+1)).text(_dataList[i].getStringValue(\"photo_title\"));\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t$(\"#ct\"+(i+1)).attr(\"href\",_dataList[i].getStringValue(\"photo_link\"));\n");
      out.write("\t\t\t$(\"#h\"+(i+1)).attr(\"href\",_dataList[i].getStringValue(\"photo_link\"));\n");
      out.write("\t\t}\t\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("query2();\n");
      out.write("\n");
      out.write("function query2(){\n");
      out.write("\tvar xco=new XCO();\n");
      out.write("\txco.setIntegerValue(\"photo_type\", 1);\n");
      out.write("\t\tvar options ={\n");
      out.write("\t\t\turl:\"/index/photolist.jhtml\",\n");
      out.write("\t\t\tdata:xco,\n");
      out.write("\t\t\tsuccess: manage2\n");
      out.write("\t};\n");
      out.write("\t$.doXcoRequest(options);\t\t\t\t\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("//渲染单个对象\n");
      out.write("function manage2(xco){\n");
      out.write("\tvar total = 0;\n");
      out.write("\tif(xco.getIntegerValue(\"total\")){\n");
      out.write("\t\ttotal = xco.getIntegerValue(\"total\");\n");
      out.write("\t}\n");
      out.write("    var _dataList = xco.getXCOListValue(\"data\");\n");
      out.write("    if(_dataList){\n");
      out.write("\t\tfor ( var i = 0; i < _dataList.length; i++) {\n");
      out.write("\t\t\t$(\"#l\"+(i+1)).attr(\"alt\",_dataList[i].getStringValue(\"photo_title\"));\n");
      out.write("\t\t\t$(\"#l\"+(i+1)).attr(\"src\",_dataList[i].getStringValue(\"photo_src\"));\n");
      out.write("\t\t\t$(\"#lb\"+(i+1)).attr(\"href\",_dataList[i].getStringValue(\"photo_link\"));\n");
      out.write("\t\t}\t\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("queryNews();\n");
      out.write("\n");
      out.write("function queryNews(){\n");
      out.write("\tvar xco=new XCO();\n");
      out.write("\txco.setIntegerValue(\"start\", 0);\n");
      out.write("\txco.setIntegerValue(\"flag\", 2);\n");
      out.write("\txco.setIntegerValue(\"pageSize\", 4);\n");
      out.write("\t\tvar options ={\n");
      out.write("\t\t\turl:\"/news/newslist.jhtml\",\n");
      out.write("\t\t\tdata:xco,\n");
      out.write("\t\t\tsuccess: manageNews\n");
      out.write("\t};\n");
      out.write("\t$.doXcoRequest(options);\t\t\t\t\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("//渲染单个对象\n");
      out.write("function manageNews(xco){\n");
      out.write("\t//alert(xco);\n");
      out.write("\tvar total = 0;\n");
      out.write("\tif(xco.getIntegerValue(\"total\")){\n");
      out.write("\t\ttotal = xco.getIntegerValue(\"total\");\n");
      out.write("\t}\n");
      out.write("\t$(\"#news\").html(\"\");\n");
      out.write("    var _dataList = xco.getXCOListValue(\"data\");\n");
      out.write("    if(_dataList){\n");
      out.write("\t\tfor ( var i = 0; i < _dataList.length; i++) {\n");
      out.write("\t\t\t$(\"#news\").append('<li>'\n");
      out.write("\t\t\t\t\t+'<a href=\"jxdtinfo.jsp?id='+_dataList[i].getLongValue(\"id\")+'\">'+renderJXDT(_dataList[i].getStringValue(\"title\"))+'</a>'\n");
      out.write("\t\t\t\t\t+'<span>'+render(_dataList[i].getStringValue(\"create_time\"))+'</span>'\n");
      out.write("\t\t\t\t\t+'</li>');\n");
      out.write("\t\t}\t\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function renderJXDT(title){\n");
      out.write("\tif(title.length > 24){\n");
      out.write("\t\ttitle = title.substring(0,24);\n");
      out.write("\t}\n");
      out.write("\treturn title;\n");
      out.write("}\n");
      out.write("\n");
      out.write("function renderJXTZ(title){\n");
      out.write("\tif(title.length > 12){\n");
      out.write("\t\ttitle = title.substring(0,12);\n");
      out.write("\t}\n");
      out.write("\treturn title;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function render(time){\n");
      out.write("\tvar month = time.substring(5,7);\n");
      out.write("\tvar day = time.substring(8,10);\n");
      out.write("\treturn \"[\"+month+\"-\"+day+\"]\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("queryMessage();\n");
      out.write("\n");
      out.write("function queryMessage(){\n");
      out.write("\tvar xco=new XCO();\n");
      out.write("\txco.setIntegerValue(\"start\", 0);\n");
      out.write("\txco.setIntegerValue(\"pageSize\", 5);\n");
      out.write("\t\tvar options ={\n");
      out.write("\t\t\turl:\"/message/messagelist2.jhtml\",\n");
      out.write("\t\t\tdata:xco,\n");
      out.write("\t\t\tsuccess: manageMessage\n");
      out.write("\t};\n");
      out.write("\t$.doXcoRequest(options);\t\t\t\t\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("//渲染单个对象\n");
      out.write("function manageMessage(xco){\n");
      out.write("\t//alert(xco);\n");
      out.write("\tvar total = 0;\n");
      out.write("\tif(xco.getIntegerValue(\"total\")){\n");
      out.write("\t\ttotal = xco.getIntegerValue(\"total\");\n");
      out.write("\t}\n");
      out.write("\t$(\"#message\").html(\"\");\n");
      out.write("    var _dataList = xco.getXCOListValue(\"data\");\n");
      out.write("    if(_dataList){\n");
      out.write("\t\tfor ( var i = 0; i < _dataList.length; i++) {\n");
      out.write("\t\t\t$(\"#message\").append('<li>'\n");
      out.write("\t\t\t\t\t+'<a href=\"zytzinfo.jsp?id='+_dataList[i].getLongValue(\"message_id\")+'\">'+renderJXTZ(_dataList[i].getStringValue(\"message_name\"))+'</a>'\n");
      out.write("\t\t\t\t\t+'<span>'+render(_dataList[i].getStringValue(\"create_time\"))+'</span>'\n");
      out.write("\t\t\t\t\t+'</li>');\n");
      out.write("\t\t}\t\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function render2(time){\n");
      out.write("\tvar month = time.substring(5,7);\n");
      out.write("\tvar day = time.substring(8,10);\n");
      out.write("\treturn \"[\"+month+\"-\"+day+\"]\";\n");
      out.write("}\n");
      out.write("$(document).keydown(function(e) {  \n");
      out.write("    if (e.keyCode == 13) {  \n");
      out.write("    \tdoLogin();\n");
      out.write("    }  \n");
      out.write("});  \n");
      out.write("//登录\n");
      out.write("function doLogin(){\n");
      out.write("\tvar xco = new XCO();\n");
      out.write("\tvar user_name = $(\"#UserName\").val();\n");
      out.write("\tif(user_name){\n");
      out.write("\t\txco.setStringValue(\"user_name\",user_name);\n");
      out.write("\t}else{\n");
      out.write("\t\t$(\"#user_name_msg\").show();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tvar password = $(\"#PassWord\").val();\n");
      out.write("\tif(password){\n");
      out.write("\t\txco.setStringValue(\"password\",password);\n");
      out.write("\t}else{\n");
      out.write("\t\t$(\"#password_msg\").show();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tvar verifyCode = $(\"#verifycode\").val();\n");
      out.write("\tif(verifyCode){\n");
      out.write("\t\txco.setStringValue(\"verifyCode\",verifyCode);\n");
      out.write("\t}else{\n");
      out.write("\t\t$(\"#verifycode_msg\").show();\n");
      out.write("\t}\n");
      out.write("\txco.setIntegerValue(\"type\", $(\"#Question\").val());\n");
      out.write("\tif(xco.getStringValue(\"user_name\") && xco.getStringValue(\"password\") && xco.getStringValue(\"verifyCode\") && xco.getIntegerValue(\"type\")){\n");
      out.write("\t\tvar options ={\n");
      out.write("\t\t\t\turl:\"/login/login.jhtml\",\n");
      out.write("\t\t\t\tdata:xco,\n");
      out.write("\t\t\t\tsuccess: manage\n");
      out.write("\t\t};\n");
      out.write("\t\t//if(K1mTokenFindDevice()){\n");
      out.write("\t\t\t$.doXcoRequest(options);\n");
      out.write("\t\t//}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("function manage(xco){\n");
      out.write("\t//alert(xco.getObjectValue(\"data\"));\n");
      out.write("\tif(xco.getCode() == 0){\n");
      out.write("\t\tvar type = xco.getObjectValue(\"data\").getObjectValue(\"type\");\n");
      out.write("\t\tif(type == 1){\n");
      out.write("\t\t\twindow.location.href=\"/view/message/msglist.jsp\";\n");
      out.write("\t\t}else if(type == 2){\n");
      out.write("\t\t\twindow.location.href=\"/view/message/msglist.jsp\";\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t//window.location.href=\"/view/message/sendmsg.jsp\";\n");
      out.write("\t\t\twindow.location.href=\"view/message/msgadminlist.jsp\";\n");
      out.write("\t\t}\n");
      out.write("\t}else if(xco.getCode() == 1){\n");
      out.write("\t\t $(\"#verifyCode\").val(\"\");\n");
      out.write("\t\tvar mes = xco.getMessage();\n");
      out.write("\t\talert(mes);\n");
      out.write("\t}else{\n");
      out.write("\t\tvar mes = xco.getMessage();\n");
      out.write("\t\talert(mes);\n");
      out.write("\t}\n");
      out.write("\tverifyFun();\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
